packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: install

catalog:
  typescript: ^5.9.2

catalogMode: prefer

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - '@oxlint/*'
  - '@vitejs/*'
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - rolldown-vite
  - top-github-dependents-by-stars
  - tsdown
  - vite
  - vitepress
  - vitest
  - vitest
  - playwright
  - playwright-core
