packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: install

catalog:
  vite: "^7.2.4"
  typescript: ^5.9.2

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - '@oxfmt/*'
  - '@oxlint-tsgolint/*'
  - '@oxlint/*'
  - '@oxc-minify/*'
  - '@oxc-parser/*'
  - '@oxc-resolver/*'
  - '@oxc-transform/*'
  - '@oxc-project/*'
  - '@rolldown/*'
  - '@rolldown/pluginutils'
  - 'oxfmt'
  - 'oxlint'
  - 'oxlint-tsgolint'
  - 'rolldown'
  - 'rolldown-plugin-dts'
  - 'rolldown-vite'
  - 'tsdown'
  - 'vite'
  - 'vitepress'
  - 'vitest'
  - '@vitest/*'

overrides:
  "vite": "npm:@voidzero-dev/vite-plus-core"
  "vitest": "npm:@voidzero-dev/vite-plus-test"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - dprint
  - esbuild

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    oxc-minify: '*'
