packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: install

catalog:
  typescript: ^5.9.2

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus'
  - '@oxfmt/*'
  - '@oxlint-tsgolint/*'
  - '@oxlint/*'
  - '@oxc-project/*'
  - '@rolldown/*'
  - '@rolldown/pluginutils'
  - 'oxfmt'
  - 'oxlint'
  - 'oxlint-tsgolint'
  - 'rolldown'
  - 'rolldown-plugin-dts'
  - 'rolldown-vite'
  - 'tsdown'
  - 'vite'
  - 'vitepress'
  - 'vitest'
  - '@vitest/*'
