packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: install

catalog:
  typescript: ^5.9.2

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus'
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - rolldown-vite
  - top-github-dependents-by-stars
  - tsdown
  - vite
  - vitepress
  - vitest
  - vitest
