name: Setup Node and pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "lts/*"
        registry-url: "https://registry.npmjs.org"
        package-manager-cache: false
        check-latest: true
        # see pnpm cache setting below
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Get pnpm store directory
      id: store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Save and restore pnpm cache on main
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      if: ${{ github.ref_name == 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Restore pnpm cache on PR
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      if: ${{ github.ref_name != 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
