name: Setup Node and pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: "lts/*"
        registry-url: "https://registry.npmjs.org"
        package-manager-cache: false
        # see pnpm cache setting below
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Get pnpm store directory
      id: store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Save and restore pnpm cache on main
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: ${{ github.ref_name == 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Restore pnpm cache on PR
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: ${{ github.ref_name != 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
