name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions: {}

jobs:
  ci:
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: voidzero-dev/setup-vp@e1609b468742ba9232ce5e12b3a77bdf14495277 # v1.1.0
        with:
          cache: true

      - run: npx playwright install chromium

      - name: Check
        run: vp check

      - name: Test
        run: vp test run

      - name: Build
        run: vp run build
