name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions: {}

jobs:
  ci:
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          cache: true

      - run: npx playwright install chromium

      - name: Check
        run: vp check

      - name: Test
        run: vp test run

      - name: Build
        run: vp run build
